# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 046be3f8dd4d5a15fe1f228d818bf2038958136e92e080379ad24545f867484d88b28740fd49debe24eb7b97da498bcc496f0bbf9eb2735a6f3b51ed19d50018

test:
  secret_key_base: cd630736fa2f7dac473e0afea4cbf466dcbfc501bdac2989bb218aa21dc8af9d57ca28266c2d449fc05993cdf453844d6f9408560192b3733f8896f3499d93de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
